Install cidmaps by default
fontforge/fontforge pull request #4707
Opened 2021-04-15 14:03 UTC by ctrlcctrlv

There's no reason not to do this. We already distribute them as part of
the repository.

* Closes #4411.
* Closes #4350.
* Related also to #1831. After we make it so we're installing the
  cidmaps in the repo, it would make sense to assure that they're
  actually the most up-to-date ones.

### Type of change

- **Bug fix**
- **Non-breaking change**

2021-06-30 14:16 UTC, frank-trampe commented on fontforge/encoding.c
> -		    getFontForgeShareDir()==NULL?"/usr/share/fontforge":getFontForgeShareDir()
Why drop the path?

2021-06-30 14:22 UTC, frank-trampe commented on fontforgeexe/startui.c
> +	GGadgetSetImageDir( getPixmapDir() );
GGadgetSetImageDir leaves its argument untouched. I think that we need to free it here.

2021-07-11 11:56 UTC, jtanx requested changes
These are the changes I would make


```patch
diff --git a/contrib/cidmap/CMakeLists.txt b/contrib/cidmap/CMakeLists.txt
index 709a4de6c..88f20e0fd 100644
--- a/contrib/cidmap/CMakeLists.txt
+++ b/contrib/cidmap/CMakeLists.txt
@@ -1,22 +1,29 @@
 # Distributed under the original FontForge BSD 3-clause license
 
 if(ENABLE_MAINTAINER_TOOLS)
-    add_executable(mapcns1 src/mapcns1.c)
-    add_executable(mapgb1 src/mapgb1.c)
-    add_executable(mapjapan1 src/mapjapan1.c)
-    add_executable(mapjapan2 src/mapjapan2.c)
-    add_executable(mapkorean src/mapkorean.c)
+  add_executable(mapcns1 src/mapcns1.c)
+  add_executable(mapgb1 src/mapgb1.c)
+  add_executable(mapjapan1 src/mapjapan1.c)
+  add_executable(mapjapan2 src/mapjapan2.c)
+  add_executable(mapkorean src/mapkorean.c)
 
-    target_link_libraries(mapcns1 PRIVATE fontforge)
-    target_link_libraries(mapgb1 PRIVATE fontforge)
-    target_link_libraries(mapjapan1 PRIVATE fontforge)
-    target_link_libraries(mapjapan2 PRIVATE fontforge)
-    target_link_libraries(mapkorean PRIVATE fontforge)
+  target_link_libraries(mapcns1 PRIVATE fontforge)
+  target_link_libraries(mapgb1 PRIVATE fontforge)
+  target_link_libraries(mapjapan1 PRIVATE fontforge)
+  target_link_libraries(mapjapan2 PRIVATE fontforge)
+  target_link_libraries(mapkorean PRIVATE fontforge)
 endif()
 
-file(GLOB_RECURSE cidmaps *.cidmap)
-
 install(
-    FILES ${cidmaps}
-    DESTINATION ${CMAKE_INSTALL_DATADIR}/fontforge/cidmap
+  FILES
+    Adobe-CNS1-6.cidmap
+    Adobe-GB1-5.cidmap
+    Adobe-Identity-0.cidmap
+    Adobe-Japan1-5.cidmap
+    Adobe-Japan1-6.cidmap
+    Adobe-Japan1-7.cidmap
+    Adobe-Japan2-0.cidmap
+    Adobe-Korea1-2.cidmap
+  DESTINATION ${CMAKE_INSTALL_DATADIR}/fontforge/cidmap
+  COMPONENT cidmaps
 )
-- 
2.32.0

```


```patch
diff --git a/fontforge/encoding.c b/fontforge/encoding.c
index 0f99dda7f..e22caf958 100644
--- a/fontforge/encoding.c
+++ b/fontforge/encoding.c
@@ -1095,7 +1095,7 @@ return( ret );
 struct cidmap *FindCidMap(char *registry,char *ordering,int supplement,SplineFont *sf) {
     struct cidmap *map, *maybe=NULL;
     char *file;
-    char *maybefile=NULL;
+    char *maybefile=NULL, *sharedir=NULL;
     int maybe_sup = -1;
     const char *buts[3], *buts2[3], *buts3[3];
     char *buf = NULL;
@@ -1117,8 +1117,8 @@ return( map );
 return( maybe );	/* User has said it's ok to use maybe at this supplement level */
 
     file = SearchDirForCidMap(".",registry,ordering,supplement,&maybefile);
-    char* sharedir = getShareSubDir("/cidmap");
     if ( file==NULL ) {
+	sharedir = getShareSubDir("/cidmap");
 	file = SearchDirForCidMap(sharedir,registry,ordering,supplement,&maybefile);
     }
 
@@ -1157,7 +1157,8 @@ return( maybe );
 	buf = smprintf( "%s-%s-*.cidmap", registry, ordering );
 	if ( maybe==NULL && maybefile==NULL ) {
 	    buts3[0] = _("_Browse"); buts3[1] = _("_Give Up"); buts3[2] = NULL;
-	    ret = ff_ask(_("No cidmap file..."),(const char **)buts3,0,1,_("FontForge was unable to find a cidmap file for this font. It is not essential to have one, but some things will work better if you do. Would you like to search your local disk for an appropriate file?"));
+	    ret = ff_ask(_("No cidmap file..."),(const char **)buts3,0,1,_("FontForge was unable to find a cidmap file for this font. The following path was searched:\n   %.80s\n\nIt is not essential to have one, but some things will work better if you do. Would you like to search your local disk for an appropriate file?"),
+	    sharedir);
 	    if ( ret==1 || no_windowing_ui )
 		buf = NULL;
 	}
diff --git a/fontforgeexe/startui.c b/fontforgeexe/startui.c
index 77f1080e1..cddf149a8 100644
--- a/fontforgeexe/startui.c
+++ b/fontforgeexe/startui.c
@@ -1080,11 +1080,13 @@ int fontforge_main( int argc, char **argv ) {
     textdomain("FontForge");
     GResourceUseGetText();
     {
-	GGadgetSetImageDir( getPixmapDir() );
+	char* path = getPixmapDir();
+	GGadgetSetImageDir( path );
+    free(path);
 
-	char* resource_filename = getShareSubDir("/resources/fontforge.resource");
-	GResourceAddResourceFile(resource_filename, GResourceProgramName,false);
-	free(resource_filename);
+	path = getShareSubDir("/resources/fontforge.resource");
+	GResourceAddResourceFile(path, GResourceProgramName,false);
+	free(path);
     }
     hotkeysLoad();
 //    loadPrefsFiles();
diff --git a/gutils/fsys.c b/gutils/fsys.c
index 3f8411ccf..a3689cb14 100644
--- a/gutils/fsys.c
+++ b/gutils/fsys.c
@@ -49,7 +49,7 @@
 
 static char *program_dir = NULL;
 static char dirname_[MAXPATHLEN+1];
-static char *FONTFORGE_SHARE_SUBDIR = "/share/fontforge";
+static const char *FONTFORGE_SHARE_SUBDIR = "/share/fontforge";
 
 /**
  * \brief Removes the extension from a file path, if it exists.
@@ -835,7 +835,7 @@ void FindProgDir(char *prog) {
 // When calling this function, make sure you prepend "/" to the subdirectory
 // you want. So, to get e.g. /usr/share/cidmaps, call
 // getShareSubDir("/cidmaps").
-char *getShareSubDir(char* subdir) {
+char *getShareSubDir(const char* subdir) {
     char *sharedir, *pt;
     int len;
 
diff --git a/inc/gfile.h b/inc/gfile.h
index dddec327c..d09a5e729 100644
--- a/inc/gfile.h
+++ b/inc/gfile.h
@@ -98,7 +98,7 @@ extern char *GFileReadAll(char *name);
 extern int   GFileWriteAll(char *filepath, char *data);
 extern void  FindProgDir(char *prog);
 extern char *getShareDir();
-extern char *getShareSubDir(char* subdir);
+extern char *getShareSubDir(const char* subdir);
 extern char *getLocaleDir(void);
 extern char *getPixmapDir(void);
 extern char *getHelpDir(void);
-- 
2.32.0

```

CMake changes were to keep in style with the rest (kitware style/2 space indents) and to not use globs.

Code changes just addressing a couple of the comments from Frank.

2021-10-04 08:17 UTC, pnemade commented
Can we have some progress here? Is this ready to be merged?

2021-10-05 01:16 UTC, merged

2021-10-05 14:10 UTC, pnemade commented
Thank you @jtanx